# .travis.yml
language: ruby
cache: bundler
before_install:
  - gem install bundler
script:
  - bundle exec jekyll algolia
branches:
  except:
    - master
branches:
  only:
    - code
rvm:
  - 2.4
after_success:
  - gem install jgd && jgd -b master -r code
