# .travis.yml
language: ruby
cache: bundler
before_install:
  - gem install bundler
  - gem install jgd
script:
  - bundle exec jekyll algolia
  - jgd -b master -r code
branches:
  except:
    - master
branches:
  only:
    - code
rvm:
  - 2.4
