# site settings
name: Vincent Yang
title: AeonNeo
subtitle: 
email: vincenty376+incoming@gmail.com
description: A myriad of thoughts
baseurl: # the subpath of your site, e.g. /blog
url: https://www.yangvincent.com # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: United States of America
phone: 
logo: assets/images/v4.png
locale: en_US

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 60

# social settings
500px_url:
facebook_url:
github_url: https://github.com/yangvincent
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/vinyang/
pinterest_url:
slack_url:
twitter_url: 
resume_url: https://www.yangvincent.com/resume.pdf

# build settings
markdown: kramdown
kramdown:
    audo_ids: true
    toc_levels: 1..6
    enable_coderay: false
    math_engine: mathjax

collections_dir: collections

collections:
    resources:
        output: true
        permalink: /:collection/:title/
    stories:
        output: true
        permalink: /:collection/:title/
    posts:
        output: true
        permalink: /:collection/:title/
    drafts:
        output: true
        permalink: /:collection/:title/

permalink: pretty

sass:
  style: compressed

# Google Analytics
google-analytics: UA-81484519-1

# Algolia API Key
algolia:
    application_id: 'B0GOCOINZN'
    index_name: 'prod_WEBSITE'
    search_only_api_key: '2b185b6fffab3ebfc9ecca5748aa29d9'

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store] 
